debezium/debezium-examples

- unwrap-smt/docker-compose-es.yaml
- unwrap-smt/docker-compose-jdbc.yaml
- unwrap-smt/docker-compose.yaml
Current docker-compose files are not working because the `connect-jdbc` folder has been renamed to `connect-jdbc-es`
> Fix connect-jdbc-es folder rename

- openshift/README.md
- openshift/debezium/debezium.addon
The examples should not be using files from the Strimzi master branch, which might be changing. It should use the release instead. This PR changes the links to the files from master to the 0.1.0 release. It also changes the tag for Docker images from `latest` to 0.1.0 and fixes the link to Strimzi website.
> Use Strimzi 0.1.0 release instead of master / latest

- jpa-aggregations/README.md
- jpa-aggregations/docker-compose.yaml
- jpa-aggregations/es-sink-aggregates.json
- jpa-aggregations/example-db/Dockerfile
- jpa-aggregations/example-db/schema-update.sql
- jpa-aggregations/jpa-test/pom.xml
- jpa-aggregations/jpa-test/src/main/java/io/debezium/aggregation/connect/KafkaConnectArraySchemaSerializer.java
- jpa-aggregations/jpa-test/src/main/java/io/debezium/aggregation/connect/KafkaConnectObjectSchemaSerializer.java
- jpa-aggregations/jpa-test/src/main/java/io/debezium/aggregation/connect/KafkaConnectSchemaFactoryWrapper.java
- jpa-aggregations/jpa-test/src/main/java/io/debezium/aggregation/connect/KafkaConnectSchemaSerializer.java
- jpa-aggregations/jpa-test/src/main/java/io/debezium/aggregation/hibernate/Aggregate.java
- jpa-aggregations/jpa-test/src/main/java/io/debezium/aggregation/hibernate/AggregationBuilderIntegrator.java
- jpa-aggregations/jpa-test/src/main/java/io/debezium/aggregation/hibernate/AggregationBuilderListener.java
- jpa-aggregations/jpa-test/src/main/java/io/debezium/aggregation/hibernate/MaterializeAggregate.java
- jpa-aggregations/jpa-test/src/main/java/io/debezium/aggregation/hibernate/ObjectMapperFactory.java
- jpa-aggregations/jpa-test/src/main/resources/META-INF/persistence.xml
- jpa-aggregations/jpa-test/src/main/resources/META-INF/services/org.hibernate.integrator.spi.Integrator
- jpa-aggregations/jpa-test/src/test/java/com/example/domain/Address.java
- jpa-aggregations/jpa-test/src/test/java/com/example/domain/AddressType.java
- jpa-aggregations/jpa-test/src/test/java/com/example/domain/Category.java
- jpa-aggregations/jpa-test/src/test/java/com/example/domain/Customer.java
- jpa-aggregations/jpa-test/src/test/java/io/debezium/example/jpaaggregation/test/JpaAggregationTest.java
- jpa-aggregations/jpa-test/src/test/java/io/debezium/example/jpaaggregation/test/SerializerTest.java
- jpa-aggregations/jpa-test/src/test/resources/log4j.properties
- jpa-aggregations/json-smt-es/Dockerfile
- jpa-aggregations/json-smt-es/pom.xml
- jpa-aggregations/json-smt-es/src/main/java/io/debezium/aggregation/smt/ExpandJsonSmt.java
- jpa-aggregations/source.json
- unwrap-smt/es-sink-aggregates.json
*Update:* @jpechane, the PR is cleaned up much more now, also the README provides some basic instructions. So you could give it a try and let me know what you think :)
Hey @jpechane, here's what I've been up to these past days.
The idea is to materialize aggregates (say a customer and their addresses) within a dedicated table in the source DB and within the upstream TX. DBZ then is used to only CDC this single table, and a new SMT is used to convert the aggregates (which have been persisted as JSON) into properly typed Kafka Connect records which then can be sinked e.g. using the Elasticsearch sink connector or @hpgrahsl's MongoDB connector.
It's still very rough, but the main parts are working. To try it out, do this (the README still is not up to date):
* Build the SMT: mvn clean …
> Exploration of aggregate materialization with JPA

- kstreams/debezium-mongodb/Dockerfile
Hey, hope this PR finds you well. I was tinkering with the kstreams / ddd aggregate tutorial and noticed a few issues with it out of the box. 
The first issue I ran into, was this:
```bash
mv: cannot stat 'target/kafka-connect-mongodb-1.1.0-SNAPSHOT-jar-with-dependencies.jar': No such file or directory
```
Upon some introspection I found that the target was looking for `mongodb-1.2.0`, so I modified it accordingly and got past that error. 
(I also added the `-p` flag to the `mkdir` since it barfed my second time through the build that the directory existed.)
Secondly, when the build was complete after the above mods, and all of the containers had come up, I was able to add my MySQL connector, but was _not_ able to add my MongoDB sink connector.
I found it throwing 500's when I post the …
> Modifications to make kstreams tutorial operational out-of-the-box

- kstreams/README.md
- kstreams/docker-compose.yaml
- kstreams/poc-ddd-aggregates/Dockerfile
- kstreams/poc-ddd-aggregates/pom.xml
- kstreams/poc-ddd-aggregates/run-aggregator.sh
* One stage creates a minimal JDK with just the required modules
* One stage builds the project and adds the dependencies
* The final stage assembles all required files
As a result, the resulting image is much smaller.
> [kstreams] Making aggregator a multi-stage Docker build;

- cache-invalidation/src/main/java/io/debezium/examples/cacheinvalidation/persistence/KnownTransactions.java
Minor change to use simple cache for known transactions.
@gunnarmorling Infinispan caches within EAP are designed for internal use only, hence you're not supposed to create one there and use it for Debezium. The approach taken in the examples is right, you manage your own cache manager and caches.
Btw, I was unable to test example. After calling `mvn clean package` and `docker-compose up --build`, I tried to place an order but got an internal server error with WildFly showing:
```
order-manager_1  | Caused by: java.lang.NullPointerException
order-manager_1  | 	at io.debezium.examples.cacheinvalidation.rest.OrderResource.addOrder(OrderResource.java:35)
```
The rest of the stacktrace is [here](https://gist.github.com/galderz/c39ee57a2c003cb50d5cdaf1dd806dd3). Looking at the rest of the …
> Use simple cache for known transactions

- kstreams/poc-ddd-aggregates/run-aggregator.sh
Hey,
I just tried to start the `kstreams` example, but ran into the following error;
```
exec java -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:+ExitOnOutOfMemoryError -cp .:/opt/poc-ddd-aggregates/lib/* io.debezium.examples.aggregation.StreamingAggregatesDDD dbserver1.inventory.customers dbserver1.inventory.addresses kafka:9092
usage: java -jar <package> io.debezium.examples.aggregation.StreamingAggregatesDDD <parent_topic> <children_topic> <bootstrap_servers>
```
I was able to fix it by using separate quotation for each parameter.
> fix kstream example aggregator script

- tutorial/README.md
There is a small error in the [README documentation](https://github.com/debezium/debezium-examples/blob/master/tutorial/README.md#using-mysql-and-the-avro-message-format)
The `docker-compose-mysql-avro.yaml` is missing instead we should use `docker-compose-mysql-avro-worker.yaml` or `docker-compose-mysql-avro-connector.yaml `
For this particular case doesn't matter so I've decided to use the first one
> DBZ-2059: update README.md with correct docker-compose-mysql-avro file

- auditlog/README.md
- auditlog/admin-service/pom.xml
- auditlog/admin-service/src/main/java/io/debezium/demos/auditing/admin/TransactionEvent.java
- auditlog/admin-service/src/main/java/io/debezium/demos/auditing/admin/VegetableEvent.java
- auditlog/admin-service/src/main/java/io/debezium/demos/auditing/admin/wih/SendTransactionEventWIHandler.java
- auditlog/log-enricher/pom.xml
- auditlog/log-enricher/src/main/java/io/debezium/demos/auditing/enricher/ChangeEventEnricher.java
- auditlog/vegetables-service/pom.xml
* Kafka Streams 2.3 brought an incompatability around state stores, hence the change to TimestampedKeyValueStore (see https://kafka.apache.org/23/documentation/streams/upgrade-guide#streams_api_changes_230)
* The Kogito admin service needed updating to ignore the new "transaction" field and use latest MP Reactive Messaging APIs
@Naros, could you check out this one? Note there's still one issue with the admin service, it currently fails to send the TX metadata events to Kafka. I'm discussing with @cescoffier why that is.
@cescoffier, here's the stacktrace:
```
admin-service_1       | Caused by: java.lang.ClassCastException: io.smallrye.reactive.messaging.kafka.OutgoingKafkaRecord cannot be cast to java.lang.String
admin-service_1       | 	at …
```
> [auditlog] Upgrading to current version of Debezium and Quarkus;

- graphql/README.md
- graphql/aggregator/pom.xml
- graphql/example-db/Dockerfile
- graphql/ws-client/pom.xml
* Update Debezium to 1.2
* Update Apache Kafka to 2.5.0
* Update Java WebSocket to 1.5.1
This PR supersedes PR #112 to bring other components and versions up-to-date.
> [graphql] Update dependencies

- cache-invalidation/Dockerfile
- cache-invalidation/pom.xml
- cache-invalidation/resources/wildfly/customization/commands.cli
- cache-invalidation/src/main/webapp/WEB-INF/jboss-deployment-structure.xml
* Update Debezium to 1.2.5.Final
* Update WildFly to 20.0.1
* Update Infinispan to 10.1.0.Final
* Update PostgreSQL driver to 42.2.9
This PR supersedes PR #89 as additional components needed to be upgraded.
> [cache-invalidation] Update dependencies

- tutorial/debezium-db2-init/db2server/Dockerfile
- tutorial/debezium-db2-init/db2server/custom-init/cleanup_storage.sh
- tutorial/debezium-db2-init/db2server/dbsetup.sh
- tutorial/debezium-db2-init/db2server/openshift_entrypoint.sh
Adds entry-point script for OCP with the ability to execute scripts prior to any other db setup. 
Unforuntale DB2 in OCP seems to have issues to start when database directory in emptyDIr volume is not empty and for some reason that happens sometimes.
> DBZ-2693 Added entry-point script for OCP environment

- tutorial/debezium-vitess-init/Dockerfile
https://issues.redhat.com/browse/DBZ-3100
Related PRs:
- Vitess Connector Documentation: https://github.com/debezium/debezium/pull/2121
- Compatibility matrix on the website: https://github.com/debezium/debezium.github.io/pull/639
> DBZ-3100 Vitess Connector supports Vitess 9.0.0

- outbox/debezium-strimzi/Dockerfile
- outbox/pom.xml
The otubox example is no longer buildable du to quarkas changes. This PR aligns dependencies and versions to the latest stable Debezium.
@gunnarmorling One quick fix
> Update outbox to the latest stable

- monitoring/debezium-grafana/debezium-dashboard.json
- monitoring/debezium-grafana/debezium-mysql-connector-dashboard.json
Strimzi, Kafka on Kubernetes, also generates records with property-names like _name. The regexp was not restricted enough, so it would return values of that property, instead of the property name.
> Regexp restrictied, so patterns like _name are ignored

- monitoring/debezium-grafana/debezium-dashboard.json
- monitoring/debezium-grafana/debezium-mysql-connector-dashboard.json
When using debezium-mysql-connector, the context of binlog/streaming events has the value binlog instead of streaming.
Using this change in the dashboard both events are displayed. Arguably, a rewrite rule could in monitoring/debezium-jmx-exporter/config.yml could also work, but using a regular expression seems simpler and less drastic.
> Allow dashboard to work with mysql/mariadb events

- monitoring/docker-compose.yml
JMX metrics of the Kafka Connect worker don't seem to be available with the current configuration. According to image source code (e.g. https://github.com/debezium/docker-images/pull/223) and the [documentation](https://debezium.io/documentation/reference/operations/monitoring.html#kafka-connect-jmx-environment-variables-docker), it should be `JMXPORT` (not `JMX_PORT`) and `JMXHOST`.
> Fix JMX configuration for Kafka Connect

- debezium-server-mongo-pubsub/README.md
- debezium-server-mongo-pubsub/conf/application.properties
- debezium-server-mongo-pubsub/dbz-server-compose.yml
- debezium-server-mongo-pubsub/mongo-compose.yml
Add new example on how to start and run Debezium Server using MongoDB and GCP Pub/Sub.
There are not much examples using Debezium Server, and as a person who recently started with Debezium, I missed more step-by-step tutorials on this.
> Add debezium server example using MongoDB and PubSub

- tutorial/README.md
With Docker Compose version v2.0.0, the name of the container running the SQL Server instance is `tutorial-sqlserver-1`, not `tutorial_sqlserver_1`:
```
$ env DEBEZIUM_VERSION=1.7 docker compose -f docker-compose-sqlserver.yaml up
[+] Running 5/5
⠿ Network tutorial_default        Created                                                                                             0.1s
⠿ Container tutorial-zookeeper-1  Created                                                                                             0.1s
⠿ Container tutorial-sqlserver-1  Created                                                                                             0.1s
⠿ Container tutorial-kafka-1      Created …
```
> Use docker-compose when initializing SQL Server database

- cloudevents/docker-compose.yaml
- end-to-end-demo/docker-compose.yaml
- tutorial/docker-compose-mysql-avro-connector.yaml
- tutorial/docker-compose-mysql-avro-worker.yaml
Adds kafkastore.bootstrap.servers to the schema-registry container compose configs. This config option is required in [confluentinc/cp-schema-registry:7.0.0](https://docs.confluent.io/platform/7.0.0/schema-registry/installation/config.html#kafkastore-connection-url) which is being pulled in when the avro examples are run without a local cached version of an older image.  For the purpose of these standalone examples I believe it should be ok to keep the zookeeper connection config around so older versions will still work, but happy to clean it up if it is desired.
> DBZ-4666 - Add kafkastore.bootstrap.servers configs to schema-registry containers

- tutorial/debezium-db2-init/db2connect/Dockerfile
Fixed Dockerfile for db2 example using [base](https://github.com/debezium/docker-images/blob/b102abeea2c724d16b936ad5951568bac8ffde40/connect-base/1.9/Dockerfile#L6) as a reference. 
Error:
```
ERROR [2/3] RUN yum -y install libaio curl && yum clean all
[2/3] RUN yum -y install libaio curl && yum clean all:
#6 0.302 /bin/sh: line 1: yum: command not found
```
> Fixed db2 example

- cloudevents/README.md
- cloudevents/docker-compose.yaml
- distributed-caching/README.md
- end-to-end-demo/README.md
- end-to-end-demo/debezium-hiking-demo/resources/wildfly/customization/commands.cli
- end-to-end-demo/docker-compose.yaml
- kstreams-live-update/demo-os.md
- kstreams-live-update/demo.md
- saga/README.md
- tutorial/docker-compose-mysql-avro-connector.yaml
- tutorial/docker-compose-mysql-avro-worker.yaml
* replace outdated the `--zookeeper` option with the `--bootstrap-server` option
* remove `SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL`
* pin the version of the Confluent registry image
* fix end-to-end demo
https://issues.redhat.com/browse/DBZ-4660
> Remove obsolete Kafka option

- ui-demo/docker-compose.yaml
As per documentation:
https://debezium.io/documentation/reference/stable/operations/debezium-ui.html
The correct naming for the parameter is KAFKA_CONNECT_URIS
> Correct parameter KAFKA_CONNECT_URIS

- kstreams/debezium-mongodb/Dockerfile
* Currently, dockerfile for kstreasm example is not working due to Debezium docker image is using fedora minimal image, which does not include yum.
* The purpose of this tiny PR is to fix that replacing it for microdnf.
> Fix dockerfile using microdnf instead of yum

- kstreams/poc-ddd-aggregates/Dockerfile
* Currently DDD dockerfile is not working due to fedora registry image 29 not being present anymore.
* In this PR I upgrade it to 32
* Current tags [link](https://registry.fedoraproject.org/repo/fedora-minimal/tags/)
> Fix kstreams dockerfile to bump fedora-minimal to a version available

- outbox/debezium-strimzi/Dockerfile
- outbox/docker-compose.yaml
- outbox/order-service/pom.xml
- outbox/pom.xml
https://issues.redhat.com/browse/DBZ-5174
Updates version of Debezium and Strimzi to latest stable releases for outbox example.
> DBZ-5174 Updated to Strimzi 0.29 and Debezium 1.9

- debezium-server-name-mapper/README.md
- debezium-server-name-mapper/pom.xml
- debezium-server-name-mapper/src/main/resources/application.properties
This one was failing with [missing method](https://github.com/a0x8o/kafka/blob/master/clients/src/main/java/org/apache/kafka/common/utils/Utils.java#L1442). This method is not present in kafka-clients:3.1 (which is defined in quarkus' BOM). The exclusion and manual alignment seems to do the trick, although I'm not sure if this should be the solution
> [Debezium Server NameMapper PubSub] Switch to Debezium 2.0

- kstreams/README.md
Hello I was reading the doc and saw that there was a missing `]` there.
> Fix markdown typo

- ui-demo/docker-compose.yaml
Missing environment variable for enabling Debezium Kafka Connect Rest Extension
> Enable Debezium Kafka Connect Rest Extension

- debezium-server/debezium-server-mysql-redis-pubsub/Dockerfile
- debezium-server/debezium-server-mysql-redis-pubsub/README.md
- debezium-server/debezium-server-mysql-redis-pubsub/config-mysql/application.properties
- debezium-server/debezium-server-mysql-redis-pubsub/docker-compose.yml
Related to https://github.com/debezium/debezium/pull/5731
This example has two objectives:
1. Try Redis as `RedisOffsetBackingStore` and `RedisSchemaHistory`. By stopping and restarting Redis, I managed to reproduce the issue in https://issues.redhat.com/browse/DBZ-7879
2. Although we do have an example with Pub/Sub in `debezium-server/debezium-server-sink-pubsub`,  it requires GCP project with authentication, which is not ideal for local testing
-> This example Pub/Sub emulator instead
> Add tutorial for Debezium Server with Redis and Pub/Sub emulator

- tutorial/README.md
- tutorial/register-mysql-apicurio-compatibile-converter-avro.json
The documentation on Avro schema registry has two sections - Apicurio registry and Confluent registry.   However it doesn't have anything for Apicurio in "compatibility mode". 
we added a new section and configuration that enable the compatibility mode.
> DBZ-8945: Apicurio registry configuration should include instructions for confluent compatibility mode

- debezium-server/debezium-server-sink-pubsub/README.md
- debezium-server/debezium-server-sink-pubsub/docker-compose.yml
- mongodb-outbox/README.md
- mongodb-outbox/docker-compose.yaml
- tutorial/README.md
- tutorial/docker-compose-mongodb.yaml
- unwrap-mongodb-smt/README.md
- unwrap-mongodb-smt/docker-compose.yaml
Relates to https://github.com/debezium/container-images/pull/455
Tutorial works
unwrap requires an image which I am not able to test at the moment due to platform incompatibility (pg example image supposedly) 
Outbox example fails with 
```
onnect-1       | [2025-05-26 12:59:40,109] ERROR [outbox-connector|task-0] Failed to start task outbox-connector-0 (org.apache.kafka.connect.runtime.Worker:652)
connect-1       | org.apache.kafka.common.KafkaException: Failed to construct kafka producer
connect-1       | 	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:465)
connect-1       | 	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:290)
connect-1       | 	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:273) …
```
> [mongo-images] improved rs initialisation for compose environments

- sql-server-read-replica/README.md
This pull request updates the sql-server-read-replica README file in the Debezium SQL Server example to reflect changes in the sqlcmd tool path, add support for self-signed certificates, and upgrade the Debezium version to 3.2.
- sqlcmd Path and Flag Updates:
Updated sqlcmd commands in the sql-server-read-replica README from `/opt/mssql-tools/bin/sqlcmd -U sa -P $SA_PASSWORD` to` /opt/mssql-tools18/bin/sqlcmd -U sa -P $SA_PASSWORD -C` to match the new sqlcmd tool path.
Added the `-C` flag to trust self-signed certificates, ensuring compatibility with self-hosted or development environments.
Applied these changes consistently across multiple sqlcmd commands in the sql-server-read-replica README.
- Debezium Version Bump:
Changed the exported variable in the sql-server-read-replica README …
> Update Debezium SQL Server replica README for sqlcmd path changes

- ai-rag/docker-compose.yml
It takes some time for Milvus to be fully started and in meantime DBZ server may fail to connect to Milvus, resulting into DBZ server crash.
> [ai-rag] Add Milvus health check
