tutorial/README.md, tutorial/docker-compose-mongodb.yaml, tutorial/register-mongodb.json
https://issues.jboss.org/browse/DBZ-361
=> DBZ-361 Adding tutorial Compose file for MongoDB

openshift/README.md, openshift/debezium/debezium.addon
Updating to DBZ 0.7.1 and using Strimzi resources for Kafka, Kafka-Connect and Zoopkeeper
**NOTE:** I've basically also update the content of the _included_ `addon`, similar to my PR against minishift-addon repo
=> Openshift update

unwrap-mongodb-smt/README.md, unwrap-mongodb-smt/debezium-jdbc/Dockerfile, unwrap-mongodb-smt/docker-compose.yaml, unwrap-mongodb-smt/jdbc-sink.json, unwrap-mongodb-smt/mongodb-source.json
https://issues.jboss.org/browse/DBZ-567
=> DBZ-567 Adding example for MongoDB flattening SMT

unwrap-mongodb-smt/README.md
* Run docker-compose in background
* Exported CURRENT_HOST variable for docker-machine virtual & local machine
* Amended connector commands in order to use CURRENT_HOST variable
=> Updated README.md

tutorial/README.md, tutorial/debezium-sqlserver-init/inventory.sql, tutorial/docker-compose-sqlserver.yaml, tutorial/register-sqlserver.json
https://issues.jboss.org/browse/DBZ-40
=> DBZ-40 SQL Server usage example

jpa-aggregations/jpa-test/src/main/java/io/debezium/aggregation/connect/KafkaConnectSchemaFactoryWrapper.java, jpa-aggregations/jpa-test/src/main/java/io/debezium/aggregation/hibernate/AggregationBuilderListener.java
@jpechane Minor fall-out of integrating the PoC into the lab.
=> [jpa-aggregations] Remove reference to Customer entity

kstreams-live-update/README.md, kstreams-live-update/aggregator/Dockerfile, kstreams-live-update/aggregator/pom.xml, kstreams-live-update/aggregator/src/main/java/io/debezium/examples/kstreams/liveupdate/aggregator/StreamsPipelineManager.java, kstreams-live-update/aggregator/src/main/java/io/debezium/examples/kstreams/liveupdate/aggregator/health/AggregatorStarted.java, kstreams-live-update/debezium-es/Dockerfile, kstreams-live-update/demo-os.md, kstreams-live-update/demo.md, kstreams-live-update/docker-compose.yaml, kstreams-live-update/es-sink.json, kstreams-live-update/example-db/Dockerfile, kstreams-live-update/os-setup.sh, kstreams-live-update/os.md
Hey @jpechane, here are my demo instructions for running the KStreams demo locally (via Compose) and on OpenShift. I had maintained that in a branch in my fork but it was troublesome to rebase and I figured it's better to have the demo instructions upstream anyways. That way you and anyone else can re-use them more easily. I'll merge this myself, just wanted to point you to it :)
=> Kstreams - Demo instructions

kinesis/src/main/java/io/debezium/examples/kinesis/ChangeDataSender.java
**Type**: Bug
**Severity**: Critical
When there are delete records coming in, this program crashes because the `value` is null. So, we first need to check if the `value` (or `valueSchema`) is null, before using the value.
=> Do a null check, because the value node is null for the deletes.

graphql/aggregator/pom.xml
Motivation:
Old version of thorntail do not work with the more recent maven and produces very hard to track error. Updating to latest version solves issue. I have noticed that only for graphql example.
Before:
```
[INFO] --- thorntail-maven-plugin:2.2.0.Final:package (default) @ graphql-aggregator ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.296 s
[INFO] Finished at: 2020-01-02T17:08:06Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.thorntail:thorntail-maven-plugin:2.2.0.Final:package (default) on project graphql-aggregator: Execution default of goal …
```
=> chore: Update thorntail

monitoring/debezium-grafana/debezium-mysql-connector-dashboard.json
Created a grafana dashboard for debezium MySQL connector.
=> added debezium-mysql-connector-dashboard

.gitignore, cloudevents/README.md, cloudevents/avro-data-extractor/Dockerfile, cloudevents/avro-data-extractor/pom.xml, cloudevents/avro-data-extractor/src/main/java/io/debezium/examples/cloudevents/dataextractor/StreamsPipelineManager.java, cloudevents/avro-data-extractor/src/main/java/io/debezium/examples/cloudevents/dataextractor/model/CloudEvent.java, cloudevents/avro-data-extractor/src/main/resources/application.properties, cloudevents/avro-data-extractor/src/main/resources/log4j.properties, cloudevents/docker-compose.yaml, cloudevents/register-postgres-avro-avro.json, cloudevents/register-postgres-json-avro.json, cloudevents/register-postgres-json-json.json
Example for CloudEvents support https://issues.redhat.com/browse/DBZ-1292
Requires https://github.com/debezium/debezium/pull/1198.
=> DBZ-1292 ☁️ Initial import of CloudEvents example

outbox/order-service/pom.xml
increased version of debezium-quarkus-outbox as snapshot version is not in maven repo
=> increased version of debezium-quarkus-outbox

cache-invalidation/Dockerfile, cloudevents/avro-data-extractor/pom.xml, end-to-end-demo/debezium-jdbc/Dockerfile, graphql/aggregator/pom.xml, jpa-aggregations/json-smt-es/Dockerfile, kstreams-live-update/aggregator/pom.xml, kstreams-live-update/debezium-es/Dockerfile, kstreams-live-update/os-setup.sh, kstreams/poc-ddd-aggregates/pom.xml, monitoring/debezium-jmx-exporter/Dockerfile, openshift/README.md, openshift/debezium/debezium.addon, postgres-toast/debezium-jdbc/Dockerfile, unwrap-mongodb-smt/debezium-jdbc/Dockerfile, unwrap-smt/debezium-jdbc-es/Dockerfile
https://issues.redhat.com/browse/DBZ-1741
=> DBZ-1741 use https when accessing Maven repo

tutorial/README.md, tutorial/debezium-with-apicurio/Dockerfile, tutorial/docker-compose-mysql-apicurio.yaml, tutorial/register-mysql-apicurio-converter-avro.json, tutorial/register-mysql-apicurio-converter-json.json, tutorial/register-mysql-apicurio.json
https://issues.redhat.com/browse/DBZ-1639
=> DBZ-1639 apicurio demo with both converters

unwrap-smt/README.md, unwrap-smt/debezium-jdbc-es/Dockerfile, unwrap-smt/docker-compose-es.yaml
https://issues.redhat.com/browse/DBZ-1756
=> DBZ-1756 Update unwrap-smt demo to be ES 6.1+ compatible

outbox/README.md, outbox/order-service/pom.xml, outbox/order-service/src/main/resources/application.properties, outbox/shipment-service/pom.xml
https://issues.redhat.com/browse/DBZ-1786
=> DBZ-1786 Update outbox demo

ksql/README.md, ksql/register-mysql.json, kstreams-live-update/demo-os.md, kstreams-live-update/es-sink.json, kstreams/README.md, kstreams/mysql-source.json
https://issues.redhat.com/browse/DBZ-1968
=> DBZ-1968 Adjusting to renamed SMT type

json-logging/README.md, json-logging/debezium-log4j-json/Dockerfile, json-logging/debezium-log4j-json/log4j.properties, json-logging/docker-compose.yaml, json-logging/register-mysql.json
https://issues.redhat.com/browse/DBZ-1913
=> DBZ-1913 Example of JSON formatted logs

kinesis/README.md, kinesis/pom.xml
=> [kinesis] Updating to current Debezium version

debezium-server-name-mapper/README.md, debezium-server-name-mapper/docker-compose.yaml, debezium-server-name-mapper/pom.xml, debezium-server-name-mapper/src/main/java/io/debezium/example/server/mapper/PrefixingNameMapper.java, debezium-server-name-mapper/src/main/resources/application.properties
https://issues.redhat.com/browse/DBZ-2163
=> DBZ-2163 Topic name mapper demo

tutorial/debezium-with-apicurio/Dockerfile, tutorial/docker-compose-mysql-apicurio.yaml, tutorial/register-mysql-apicurio-converter-avro.json
https://issues.redhat.com/browse/DBZ-2206
=> DBZ-2206 Upgrade apicurio to 1.2.2.Final

topic-auto-create/README.md, topic-auto-create/connector.json, topic-auto-create/docker-compose.yml
related to: https://issues.redhat.com/browse/DBZ-78 and https://github.com/debezium/debezium.github.io/pull/490
=> DBZ-78 add example for topic auto creation

distributed-caching/README.md, distributed-caching/cache-update-service/pom.xml, distributed-caching/cache-update-service/src/main/java/io/debezium/examples/caching/cacheupdater/facade/KafkaEventConsumer.java, distributed-caching/cache-update-service/src/main/java/io/debezium/examples/caching/cacheupdater/streams/TopologyProducer.java, distributed-caching/cache-update-service/src/main/java/io/debezium/examples/caching/cacheupdater/streams/model/OrderWithLines.java, distributed-caching/cache-update-service/src/main/java/io/debezium/examples/caching/commons/LocalDateTimeAdapter.java, distributed-caching/cache-update-service/src/main/java/io/debezium/examples/caching/commons/ProtoOrderLine.java, distributed-caching/cache-update-service/src/main/java/io/debezium/examples/caching/commons/ProtoOrderLineStatus.java, distributed-caching/cache-update-service/src/main/java/io/debezium/examples/caching/commons/ProtoPurchaseOrder.java, distributed-caching/cache-update-service/src/main/java/io/debezium/examples/caching/commons/PurchaseOrdersContextInitializer.java, distributed-caching/cache-update-service/src/main/resources/application.properties, distributed-caching/docker-compose.yaml, distributed-caching/infinispan-lon.xml, distributed-caching/infinispan-nyc.xml, distributed-caching/infinispan-tyo.xml, distributed-caching/order-service/pom.xml, distributed-caching/order-service/src/main/java/io/debezium/examples/caching/commons/LocalDateTimeAdapter.java, distributed-caching/order-service/src/main/java/io/debezium/examples/caching/commons/ProtoOrderLine.java, distributed-caching/order-service/src/main/java/io/debezium/examples/caching/commons/ProtoOrderLineStatus.java, distributed-caching/order-service/src/main/java/io/debezium/examples/caching/commons/ProtoPurchaseOrder.java, distributed-caching/order-service/src/main/java/io/debezium/examples/caching/commons/PurchaseOrdersContextInitializer.java, distributed-caching/order-service/src/main/java/io/debezium/examples/caching/order/model/PurchaseOrder.java, distributed-caching/order-service/src/main/java/io/debezium/examples/caching/order/rest/OrderOperationResponse.java, distributed-caching/order-service/src/main/java/io/debezium/examples/caching/order/rest/OrderResource.java, distributed-caching/order-service/src/main/java/io/debezium/examples/caching/order/service/OrderService.java, distributed-caching/order-service/src/main/resources/application.properties, distributed-caching/pom.xml
@gunnarmorling using CR1 on the client
2 order services
3 clusters 
The protoclasses are in both projects because when the quarkus app starts it loads and puts the generated protobuf in infinispan. I could not make it happen if this is in another jar (like commons jar).
=> [infinispan] adding xsite replication and protostream

kstreams-fk-join/README.md, kstreams-fk-join/aggregator/pom.xml, kstreams-fk-join/aggregator/src/main/resources/application.properties, kstreams-fk-join/register-postgres.json
@ani-sha, this does a version update for the FK join example; also the host name variable isn't needed any longer with this. Could you give this one a try? Thanks!
=> [fk-joins] Version updates

tutorial/README.md
https://issues.redhat.com/browse/DBZ-3241
=> DBZ-3241 Update Oracle tutorial, LogMiner now the default adapter

tutorial/debezium-db2-init/db2server/asncdcaddremove.sql
Fix bug when registering more than 10 DB2 tables
https://issues.redhat.com/browse/DBZ-3362
=> DBZ-3362 - Fix bug ADDTABLE Db2 CDC

monitoring/docker-compose.yml, sql-server-read-replica/debezium-sqlserver-init/Dockerfile, tutorial/docker-compose-sqlserver.yaml
https://issues.redhat.com/browse/DBZ-3379
=> DBZ-3379 Use current SQL Server container image in examples

tutorial/README.md, tutorial/docker-compose-mysql-apicurio.yaml, tutorial/register-mysql-apicurio-converter-avro.json, tutorial/register-mysql-apicurio-converter-json.json, tutorial/register-mysql-apicurio.json
https://issues.redhat.com/browse/DBZ-3171
=> DBZ-3171 Upgrade to Apicurio 2.0

.github/workflows/outbox-workflow.yml, .github/workflows/saga-workflow.yml, outbox/README.md, outbox/order-service/.dockerignore, outbox/order-service/pom.xml, outbox/order-service/src/main/docker/Dockerfile.jvm, outbox/pom.xml, outbox/shipment-service/.dockerignore, outbox/shipment-service/pom.xml, outbox/shipment-service/src/main/docker/Dockerfile.jvm, outbox/shipment-service/src/main/java/io/debezium/examples/outbox/shipment/facade/KafkaEventConsumer.java, outbox/shipment-service/src/main/resources/application.properties, saga/README.md, saga/customer-service/src/main/docker/Dockerfile.jvm, saga/customer-service/src/main/java/io/debezium/examples/saga/customer/facade/KafkaEventConsumer.java, saga/order-service/src/main/docker/Dockerfile.jvm, saga/order-service/src/main/java/io/debezium/examples/saga/framework/SagaBase.java, saga/order-service/src/main/java/io/debezium/examples/saga/order/facade/KafkaEventConsumer.java, saga/payment-service/src/main/docker/Dockerfile.jvm, saga/payment-service/src/main/java/io/debezium/examples/saga/payment/facade/KafkaEventConsumer.java, saga/pom.xml
https://issues.redhat.com/browse/DBZ-1709
=> DBZ-1709 [outbox] Upgrade to Debezium 1.6 and Quarkus 2.0

.github/workflows/apache-pulsar-workflow.yml, .github/workflows/auditlog-workflow.yml, .github/workflows/cache-invalidation-workflow.yml, .github/workflows/camel-component.yml, .github/workflows/camel-kafka-connect.yml, .github/workflows/cloudevents.yml, .github/workflows/debezium-server-name-mapper-workflow.yml, .github/workflows/distributed-caching-workflow.yml, .github/workflows/end-to-end-demo-workflow.yml, .github/workflows/graphql-workflow.yml, .github/workflows/kstreams-fk-join-workflow.yml, .github/workflows/kstreams-live-update-workflow.yml, .github/workflows/nats-workflow.yml, .github/workflows/postgres-toast-workflow.yml, .github/workflows/testcontainers-workflow.yml
https://issues.redhat.com/browse/DBZ-1749
There were a few examples that did not have any Maven bits and those do not yet have a workflow component.
=> DBZ-1749 Basic CI actions for debezium-examples

debezium-server-name-mapper/README.md, debezium-server-name-mapper/pom.xml
https://issues.redhat.com/browse/DBZ-3706
=> DBZ-3706 [debezium-server-name-mapper] Upgrade to Debezium 1.6 & Quarkus 2.0

tutorial/debezium-db2-init/db2server/Dockerfile, tutorial/debezium-db2-init/db2server/cdcsetup.sh
- More descriptive message after cdc setup completes
- Modified file permissions to match config from https://github.com/debezium/debezium-connector-db2/blob/main/src/test/docker/db2-cdc-docker/Dockerfile
- Using fixed docker tag
=> Permission issues with DB2 example image

tutorial/README.md, tutorial/docker-compose-zookeeperless-kafka-combined.yaml, tutorial/docker-compose-zookeeperless-kafka.yaml
https://issues.redhat.com/browse/DBZ-3444
@jpechane, as dicussed, I'd suggest you push only the first commit. I've added the second to facilitate testing in both modes, combined and non-combined.
=> DBZ-3444 KRaft example

outbox/README.md
Updated config syntax for dev mode Datasource since the previous one is deprecated.
=> Update outbox README.md

ui-demo/docker-compose.yaml
Modifies docker-compose.yaml for the ui-demo, to enable the connect rest extension
=> DBZ-4148 Modify ui-demo docker-compose to enable connect extension

infinispan-standalone/README.md, infinispan-standalone/debezium-with-oracle-jdbc/Dockerfile, infinispan-standalone/debezium-with-oracle-jdbc/init/inventory.sql, infinispan-standalone/docker-compose.yml, infinispan-standalone/register-oracle.json
https://issues.redhat.com/browse/DBZ-4326
=> DBZ-4326 Add Oracle with Infinispan Server Demo

apache-pulsar/README.md, apache-pulsar/pom.xml, apache-pulsar/src/main/resources/config.properties
* Fix `config.properties` to use `schema.include.list`
* Bump debezium version
* Bump Apache Pulsa version
* Fix README to show preformatted text correctly
https://issues.redhat.com/browse/DBZ-4739
=> DBZ-4739 Fix Apache Pulsar example

testcontainers/pom.xml, testcontainers/src/test/java/io/debezium/examples/testcontainers/DebeziumContainerTest.java
* Correctly resolve debezium/connect image
* Use Jupiter annotations rather than JUnit4 annotations
* Use Java 17
=> [Testcontainers] Build fixes

monitoring/register-sqlserver.json, sql-server-read-replica/register-sqlserver.json, tutorial/register-sqlserver.json
https://issues.redhat.com/browse/DBZ-5290
=> DBZ-5290 Do not use SSL with SQL Server by default

cache-invalidation/docker-compose.yaml
https://issues.redhat.com/browse/DBZ-6216
=> DBZ-6216 Use quay.io image

.github/workflows/camel-component.yml, camel-component/README.md, camel-component/docker-compose.yaml, camel-component/pom.xml, camel-component/qa-app/Dockerfile, camel-component/qa-app/src/main/docker/Dockerfile.jvm, camel-component/qa-app/src/main/java/io/debezium/examples/camel/qaapp/Answer.java, camel-component/qa-app/src/main/java/io/debezium/examples/camel/qaapp/Question.java, camel-component/qa-app/src/main/java/io/debezium/examples/camel/qaapp/rest/QuestionService.java, camel-component/qa-app/src/main/resources/application.properties, camel-component/qa-camel/Dockerfile, camel-component/qa-camel/pom.xml, camel-component/qa-camel/src/main/java/io/debezium/examples/camel/pipeline/QaDatabaseUserNotifier.java, camel-component/qa-camel/src/main/java/io/debezium/examples/camel/pipeline/Runner.java
This is only partial fix, as Camel doesn't support Debezium 2.0.0 yet, so the demo fails with wrong configuration of camel-debezium-postgres.
See https://issues.redhat.com/browse/DBZ-5725 and
https://issues.apache.org/jira/browse/CAMEL-18610
=> [Camel-component] Switch to Debezium 2.0

http-signaling-notification/README.md, http-signaling-notification/docker-compose.yaml, http-signaling-notification/initializerJson.json, http-signaling-notification/pom.xml, http-signaling-notification/register-postgres.json, http-signaling-notification/src/main/java/io/debezium/examples/notification/HttpNotificationChannel.java, http-signaling-notification/src/main/java/io/debezium/examples/signal/HttpSignalChannel.java, http-signaling-notification/src/main/resources/META-INF/services/io.debezium.pipeline.notification.channels.NotificationChannel, http-signaling-notification/src/main/resources/META-INF/services/io.debezium.pipeline.signal.channels.SignalChannelReader
https://issues.redhat.com/browse/DBZ-6478
=> DBZ-6478 HTTP Signal & Notification Example

debezium-server-mongo-pubsub/conf/application.properties, mongodb-outbox/register-mongodb.json, tutorial/register-mongodb.json, unwrap-mongodb-smt/mongodb-source.json
https://issues.redhat.com/browse/DBZ-6893
=> DBZ-6893 Migrated all MongoDB examples to mongodb.connection.string

postrges-kafka-signal/README.md, postrges-kafka-signal/connector.json, postrges-kafka-signal/docker-compose.yml
see the conversation on LinkedIn: https://www.linkedin.com/feed/update/urn:li:activity:7115665658553507840?commentUrn=urn%3Ali%3Acomment%3A%28activity%3A7115665658553507840%2C7119767027791065090%29&replyUrn=urn%3Ali%3Acomment%3A%28activity%3A7115665658553507840%2C7120710931172458496%29&dashCommentUrn=urn%3Ali%3Afsd_comment%3A%287119767027791065090%2Curn%3Ali%3Aactivity%3A7115665658553507840%29&dashReplyUrn=urn%3Ali%3Afsd_comment%3A%287120710931172458496%2Curn%3Ali%3Aactivity%3A7115665658553507840%29
=> feat(): PostgreSQL example with snapshot triggered by Kafka event

operator/tutorial-postgresql-kafka/.gitignore, operator/tutorial-postgresql-kafka/README.md, operator/tutorial-postgresql-kafka/create-environment.sh, operator/tutorial-postgresql-kafka/destroy-environment.sh, operator/tutorial-postgresql-kafka/env.sh, operator/tutorial-postgresql-kafka/infra/001_postgresql.yml, operator/tutorial-postgresql-kafka/infra/002_kafka-ephemeral.yml, operator/tutorial-postgresql-kafka/infra/010_debezium-subscription.yml, operator/tutorial-postgresql-kafka/infra/011_debezium-server-ephemeral.yml
https://issues.redhat.com/browse/DBZ-7025
=> [DBZ-7025] Debezium operator example

operator/tutorial-pubsub/.gitignore, operator/tutorial-pubsub/README.md, operator/tutorial-pubsub/create-environment.sh, operator/tutorial-pubsub/destroy-environment.sh, operator/tutorial-pubsub/env.sh, operator/tutorial-pubsub/k8s/database/001_postgresql.yml, operator/tutorial-pubsub/k8s/debezium/002_debezium-server.yml, operator/tutorial-pubsub/k8s/operator/001_subscription.yml, operator/tutorial-pubsub/olm/install.sh, operator/tutorial-pubsub/pubsub.sh, operator/tutorial-pubsub/pull.sh
https://issues.redhat.com/browse/DBZ-7370
Will be also used as a demo for Quarkus Insights
=> DBZ-7370 PubSub example for DS deployed via operator

operator/tutorial-pubsub/k8s/debezium/002_debezium-server.yml, operator/tutorial-pubsub/k8s/operator/001_subscription.yml
https://issues.redhat.com/browse/DBZ-7694
=> DBZ-7694 updated operator pub/sub examples to reflect recent CRD changes

postgres-failover-slots/00_init.sql, postgres-failover-slots/README.md, postgres-failover-slots/docker-compose.yaml, postgres-failover-slots/inventory-source.json
Requires PR https://github.com/debezium/debezium/pull/6017
=> Postgres failover slots

.github/PULL_REQUEST_TEMPLATE.md, README.md
Comprehensive list of all the examples that are part of the debezium examples repository.
closes: https://issues.redhat.com/browse/DBZ-2535
=> DBZ-2535: List all examples in root README.md

tutorial/README.md
Update sql server tutorial:
* update `sqlcmd` path
* don't use SSL
=> [tutorial] Don't use SSL when connecting to SQL server
